apiVersion: v1
metadata:
  name: backend
kind: ConfigMap

data:
  DB_HOST: mysql
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend
  namespace: expense
  labels:
    component: backend
    project: expense
    tier: app
spec:
  replicas: 2
  selector:
    matchLabels:
      component: backend
      project: expense
      tier: app
  template:
    metadata:
      labels:
        component: backend
        project: expense
        tier: app
    spec:
      containers:
        - name: backend
          image: chandrahari296/backend:v1.0

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    component: backend
    project: expense
    tier: db
  ports:
    - protocol: TCP
      port: 8080 #service-port
      targetPort: 8080 #target-port

