apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: expense
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: chandrahari296/frontend:v3.0.0          # Ensure this image exists in your DockerHub repo
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: expense
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 80  # Service listens on this port
      targetPort: 80  # Pod port
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: expense
spec:
  ingressClassName: nginx  # <-- Use this instead of the deprecated annotation
  rules:
    - host: "nginx.chaitu.org"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: nginx-service
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-spec-ingress
  namespace: expense
spec:
  rules:
    - host: "app.chaitu.org"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: nginx-service
                port:
                  number: 80