apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
    tier: database
  namespace: expense
spec:
  replicas: 3
  selector:
    matchLabels:
    app: mysql
    tier: database
  template:
    metadata:
      labels:
    app: mysql
    tier: database
    spec:
      containers:
        - name: mysql
          image: joindevops/mysql:v1.0
          ports:
            - containerPort: 80


#---
#
#apiVersion: v1
#kind: Service
#metadata:
#  name: nginx-loadbalancer
#  labels:
#    namespace: expense
#spec:
#  selector:
#    app: nginx
#  type: LoadBalancer
#  ports:
#    - protocol: TCP
#      port: 80
#      targetPort: 80
